name: dart_peer_repo
version: 1.2.0
homepage: https://www.repocket.com
description: A dart package for P2P communication.
environment:
  sdk: ^3.0.6
dependencies:
  eventify: ^1.0.1
  http: ^1.2.1
  hive: ^2.2.3
  yaml: ^3.1.2
  easy_debounce: ^2.0.3
  uuid: ^4.5.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
