
// Objective-C API for talking to the following Go packages
//
//	github.com/sagernet/sing-box/experimental/libbox
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ZenshieldBox_FRAMEWORK_H__
#define __ZenshieldBox_FRAMEWORK_H__

#include "Libbox.objc.h"
#include "Universe.objc.h"

#endif
